name: CI

on: [pull_request]

jobs:
  ci:
    runs-on: ubuntu-latest
    env:
      BUNDLE_GEMFILE: Gemfile.dev
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Ruby and install gems
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true

      - name: Run standardrb
        run: |
          bundle exec standardrb

      - name: Run tests
        run: |
          bundle exec rake test
